public enum bhc {
    NOT_ATTEMPTED,
    REJECTED_NOCREATE,
    REJECTED_NODELETE,
    REJECTED_NONFASTFORWARD,
    REJECTED_CURRENT_BRANCH,
    REJECTED_MISSING_OBJECT,
    REJECTED_OTHER_REASON,
    LOCK_FAILURE,
    OK
}
