public enum bhn {
    NOT_ATTEMPTED,
    UP_TO_DATE,
    REJECTED_NONFASTFORWARD,
    REJECTED_NODELETE,
    REJECTED_REMOTE_CHANGED,
    REJECTED_OTHER_REASON,
    NON_EXISTING,
    AWAITING_REPORT,
    OK
}
