public interface bqx {
    public static final bnm BT;
    public static final bnm DW;
    public static final bnm EQ;
    public static final bnm FH;
    public static final bnm Hw;
    public static final bnm J0;
    public static final bnm J8;
    public static final bnm Mr;
    public static final bnm P8;
    public static final bnm QX;
    public static final bnm U2;
    public static final bnm VH;
    public static final bnm Ws;
    public static final bnm XL;
    public static final bnm Zo;
    public static final bnm a8;
    public static final bnm aM;
    public static final bnm ei;
    public static final bnm er;
    public static final bnm gW;
    public static final bnm gn;
    public static final bnm j3;
    public static final bnm j6;
    public static final bnm lg;
    public static final bnm nw;
    public static final bnm rN;
    public static final bnm tp;
    public static final bnm u7;
    public static final bnm v5;
    public static final bnm vy;
    public static final bnm we;
    public static final bnm yS;

    static {
        j6 = new bnm("2.16.840.1.101.3.4");
        DW = j6.DW("2.1");
        FH = j6.DW("2.2");
        Hw = j6.DW("2.3");
        v5 = j6.DW("2.4");
        Zo = j6.DW("1");
        VH = Zo.DW("1");
        gn = Zo.DW("2");
        u7 = Zo.DW("3");
        tp = Zo.DW("4");
        EQ = Zo.DW("5");
        we = Zo.DW("6");
        J0 = Zo.DW("7");
        J8 = Zo.DW("21");
        Ws = Zo.DW("22");
        QX = Zo.DW("23");
        XL = Zo.DW("24");
        aM = Zo.DW("25");
        j3 = Zo.DW("26");
        Mr = Zo.DW("27");
        U2 = Zo.DW("41");
        a8 = Zo.DW("42");
        lg = Zo.DW("43");
        rN = Zo.DW("44");
        er = Zo.DW("45");
        yS = Zo.DW("46");
        gW = Zo.DW("47");
        BT = j6.DW("3");
        vy = BT.DW("1");
        P8 = BT.DW("2");
        ei = BT.DW("3");
        nw = BT.DW("4");
    }
}
