public interface brb {
    public static final bnm AE;
    public static final bnm AL;
    public static final bnm AR;
    public static final bnm An;
    public static final bnm BR;
    public static final bnm BT;
    public static final bnm Bx;
    public static final bnm CU;
    public static final bnm Cz;
    public static final bnm EQ;
    public static final bnm Eq;
    public static final bnm Ev;
    public static final bnm FN;
    public static final bnm Fd;
    public static final bnm Gj;
    public static final bnm Hw;
    public static final bnm I;
    public static final bnm IS;
    public static final bnm Jl;
    public static final bnm Jm;
    public static final bnm KD;
    public static final bnm Lz;
    public static final bnm MP;
    public static final bnm Mz;
    public static final bnm Nh;
    public static final bnm OW;
    public static final bnm Of;
    public static final bnm P8;
    public static final bnm PT;
    public static final bnm Pa;
    public static final bnm Q6;
    public static final bnm QO;
    public static final bnm Qq;
    public static final bnm SI;
    public static final bnm Sf;
    public static final bnm TI;
    public static final bnm U2;
    public static final bnm WB;
    public static final bnm XG;
    public static final bnm XL;
    public static final bnm XX;
    public static final bnm Xa;
    public static final bnm Z1;
    public static final bnm Za;
    public static final bnm a5;
    public static final bnm a8;
    public static final bnm aX;
    public static final bnm a_;
    public static final bnm aj;
    public static final bnm aq;
    public static final bnm b1;
    public static final bnm b_;
    public static final bnm br;
    public static final bnm cT;
    public static final bnm c_;
    public static final bnm ca;
    public static final bnm cb;
    public static final bnm ce;
    public static final bnm cn;
    public static final bnm ct;
    public static final bnm d_;
    public static final bnm dx;
    public static final bnm e3;
    public static final bnm e9;
    public static final bnm eU;
    public static final bnm e_;
    public static final bnm ef;
    public static final bnm ei;
    public static final bnm er;
    public static final bnm et;
    public static final bnm fN;
    public static final bnm fY;
    public static final bnm f_;
    public static final bnm g3;
    public static final bnm gG;
    public static final bnm gW;
    public static final bnm g_;
    public static final bnm gn;
    public static final bnm hK;
    public static final bnm h_;
    public static final bnm hz;
    public static final bnm iW;
    public static final bnm i_;
    public static final bnm jJ;
    public static final bnm jO;
    public static final bnm j_;
    public static final bnm jw;
    public static final bnm k2;
    public static final bnm kQ;
    public static final bnm k_;
    public static final bnm kf;
    public static final bnm ko;
    public static final bnm l_;
    public static final bnm lg;
    public static final bnm lp;
    public static final bnm m_;
    public static final bnm mb;
    public static final bnm n5;
    public static final bnm n_;
    public static final bnm nw;
    public static final bnm oY;
    public static final bnm oa;
    public static final bnm oy;
    public static final bnm pN;
    public static final bnm pO;
    public static final bnm q7;
    public static final bnm qP;
    public static final bnm qp;
    public static final bnm rN;
    public static final bnm ro;
    public static final bnm sE;
    public static final bnm sG;
    public static final bnm sM;
    public static final bnm sT;
    public static final bnm sg;
    public static final bnm sh;
    public static final bnm sy;
    public static final bnm tp;
    public static final bnm v5;
    public static final bnm vJ;
    public static final bnm vy;
    public static final bnm w9;
    public static final bnm wc;
    public static final bnm x9;
    public static final bnm yO;
    public static final bnm yS;
    public static final bnm ye;
    public static final bnm ys;
    public static final bnm zh;

    static {
        a_ = new bnm("1.2.840.113549.1.1");
        b_ = a_.DW("1");
        c_ = a_.DW("2");
        Hw = a_.DW("3");
        v5 = a_.DW("4");
        d_ = a_.DW("5");
        e_ = a_.DW("6");
        gn = a_.DW("7");
        f_ = a_.DW("8");
        tp = a_.DW("9");
        EQ = a_.DW("10");
        g_ = a_.DW("11");
        h_ = a_.DW("12");
        i_ = a_.DW("13");
        j_ = a_.DW("14");
        k_ = new bnm("1.2.840.113549.1.3");
        XL = k_.DW("1");
        l_ = new bnm("1.2.840.113549.1.5");
        m_ = l_.DW("1");
        n_ = l_.DW("4");
        U2 = l_.DW("3");
        a8 = l_.DW("6");
        lg = l_.DW("10");
        rN = l_.DW("11");
        er = l_.DW("13");
        yS = l_.DW("12");
        gW = new bnm("1.2.840.113549.3");
        BT = gW.DW("7");
        vy = gW.DW("2");
        P8 = new bnm("1.2.840.113549.2");
        ei = P8.DW("2");
        nw = P8.DW("4");
        SI = P8.DW("5");
        KD = P8.DW("7");
        ro = P8.DW("8");
        cn = P8.DW("9");
        sh = P8.DW("10");
        cb = P8.DW("11");
        dx = new bnm("1.2.840.113549.1.7.1");
        sG = new bnm("1.2.840.113549.1.7.2");
        ef = new bnm("1.2.840.113549.1.7.3");
        Sf = new bnm("1.2.840.113549.1.7.4");
        vJ = new bnm("1.2.840.113549.1.7.5");
        g3 = new bnm("1.2.840.113549.1.7.6");
        Mz = new bnm("1.2.840.113549.1.9");
        I = Mz.DW("1");
        ca = Mz.DW("2");
        x9 = Mz.DW("3");
        Qq = Mz.DW("4");
        sy = Mz.DW("5");
        aj = Mz.DW("6");
        lp = Mz.DW("7");
        OW = Mz.DW("8");
        br = Mz.DW("9");
        XX = Mz.DW("13");
        kQ = Mz.DW("14");
        yO = Mz.DW("15");
        XG = Mz.DW("20");
        jJ = Mz.DW("21");
        wc = Mz.DW("22.1");
        et = Mz.DW("22");
        CU = et.DW("1");
        Xa = et.DW("2");
        Eq = Mz.DW("23");
        hz = Eq.DW("1");
        aq = Mz.DW("16.3.9");
        FN = Mz.DW("15.1");
        jO = Mz.DW("15.2");
        oY = Mz.DW("15.3");
        ko = new bnm("1.2.840.113549.1.9.16.1");
        Ev = ko.DW("2");
        ye = ko.DW("4");
        WB = ko.DW("9");
        mb = ko.DW("23");
        jw = ko.DW("31");
        fY = new bnm("1.2.840.113549.1.9.16.6");
        qp = fY.DW("1");
        k2 = fY.DW("2");
        zh = fY.DW("3");
        AL = fY.DW("4");
        w9 = fY.DW("5");
        hK = fY.DW("6");
        cT = new bnm("1.2.840.113549.1.9.16.2");
        q7 = cT.DW("1");
        Z1 = cT.DW("4");
        n5 = cT.DW("5");
        Q6 = cT.DW("10");
        kf = cT.DW("11");
        Jl = cT.DW("12");
        iW = cT.DW("47");
        eU = cT.DW("7");
        e3 = cT.DW("14");
        sE = cT.DW("15");
        sg = cT.DW("16");
        pO = cT.DW("17");
        fN = cT.DW("18");
        Gj = cT.DW("19");
        Cz = cT.DW("20");
        pN = cT.DW("21");
        oy = cT.DW("22");
        aX = cT.DW("23");
        e9 = cT.DW("24");
        QO = cT.DW("25");
        sM = cT.DW("26");
        a5 = cT.DW("27");
        ys = sE;
        IS = sg;
        gG = pO;
        Nh = Gj;
        BR = new bnm("1.2.840.113549.1.9.16.5.1");
        AE = new bnm("1.2.840.113549.1.9.16.5.2");
        Za = new bnm("1.2.840.113549.1.12");
        An = Za.DW("10.1");
        Pa = An.DW("1");
        ce = An.DW("2");
        Jm = An.DW("3");
        Bx = An.DW("4");
        oa = An.DW("5");
        qP = An.DW("6");
        MP = Za.DW("1");
        Of = MP.DW("1");
        PT = MP.DW("2");
        b1 = MP.DW("3");
        AR = MP.DW("4");
        TI = MP.DW("5");
        ct = MP.DW("6");
        Fd = MP.DW("6");
        Lz = new bnm("1.2.840.113549.1.9.16.3.6");
        sT = new bnm("1.2.840.113549.1.9.16.3.7");
    }
}
