public interface bre {
    public static final bnm BT;
    public static final bnm DW;
    public static final bnm EQ;
    public static final bnm FH;
    public static final bnm Hw;
    public static final bnm J0;
    public static final bnm J8;
    public static final bnm Mr;
    public static final bnm QX;
    public static final bnm U2;
    public static final bnm VH;
    public static final bnm Ws;
    public static final bnm XL;
    public static final bnm Zo;
    public static final bnm a8;
    public static final bnm aM;
    public static final bnm er;
    public static final bnm gW;
    public static final bnm gn;
    public static final bnm j3;
    public static final bnm j6;
    public static final bnm lg;
    public static final bnm rN;
    public static final bnm tp;
    public static final bnm u7;
    public static final bnm v5;
    public static final bnm we;
    public static final bnm yS;

    static {
        j6 = new bnm("1.3.36.3");
        DW = j6.DW("2.1");
        FH = j6.DW("2.2");
        Hw = j6.DW("2.3");
        v5 = j6.DW("3.1");
        Zo = v5.DW("2");
        VH = v5.DW("3");
        gn = v5.DW("4");
        u7 = j6.DW("3.2");
        tp = u7.DW("1");
        EQ = u7.DW("2");
        we = j6.DW("3.2.8");
        J0 = we.DW("1");
        J8 = J0.DW("1");
        Ws = J8.DW("1");
        QX = J8.DW("2");
        XL = J8.DW("3");
        aM = J8.DW("4");
        j3 = J8.DW("5");
        Mr = J8.DW("6");
        U2 = J8.DW("7");
        a8 = J8.DW("8");
        lg = J8.DW("9");
        rN = J8.DW("10");
        er = J8.DW("11");
        yS = J8.DW("12");
        gW = J8.DW("13");
        BT = J8.DW("14");
    }
}
