public interface bsg {
    public static final bnm BT;
    public static final bnm CU;
    public static final bnm DW;
    public static final bnm EQ;
    public static final bnm FH;
    public static final bnm Hw;
    public static final bnm I;
    public static final bnm J0;
    public static final bnm J8;
    public static final bnm KD;
    public static final bnm Mr;
    public static final bnm Mz;
    public static final bnm OW;
    public static final bnm P8;
    public static final bnm QX;
    public static final bnm Qq;
    public static final bnm SI;
    public static final bnm Sf;
    public static final bnm U2;
    public static final bnm VH;
    public static final bnm Ws;
    public static final bnm XG;
    public static final bnm XL;
    public static final bnm XX;
    public static final bnm Xa;
    public static final bnm Zo;
    public static final bnm a8;
    public static final bnm aM;
    public static final bnm aj;
    public static final bnm br;
    public static final bnm ca;
    public static final bnm cb;
    public static final bnm cn;
    public static final bnm dx;
    public static final bnm ef;
    public static final bnm ei;
    public static final bnm er;
    public static final bnm et;
    public static final bnm g3;
    public static final bnm gW;
    public static final bnm gn;
    public static final bnm j3;
    public static final bnm j6;
    public static final bnm jJ;
    public static final bnm kQ;
    public static final bnm lg;
    public static final bnm lp;
    public static final bnm nw;
    public static final bnm rN;
    public static final bnm ro;
    public static final bnm sG;
    public static final bnm sh;
    public static final bnm sy;
    public static final bnm tp;
    public static final bnm u7;
    public static final bnm v5;
    public static final bnm vJ;
    public static final bnm vy;
    public static final bnm wc;
    public static final bnm we;
    public static final bnm x9;
    public static final bnm yO;
    public static final bnm yS;

    static {
        j6 = new bnm("1.2.840.10045");
        DW = j6.DW("1");
        FH = DW.DW("1");
        Hw = DW.DW("2");
        v5 = DW.DW("2.3.1");
        Zo = DW.DW("2.3.2");
        VH = DW.DW("2.3.3");
        gn = j6.DW("4");
        u7 = new bnm(gn + ".1");
        tp = j6.DW("2");
        EQ = tp.DW("1");
        we = gn.DW("3");
        J0 = we.DW("1");
        J8 = we.DW("2");
        Ws = we.DW("3");
        QX = we.DW("4");
        XL = j6.DW("3");
        aM = XL.DW("0");
        j3 = aM.DW("1");
        Mr = aM.DW("2");
        U2 = aM.DW("3");
        a8 = aM.DW("4");
        lg = aM.DW("5");
        rN = aM.DW("6");
        er = aM.DW("7");
        yS = aM.DW("8");
        gW = aM.DW("9");
        BT = aM.DW("10");
        vy = aM.DW("11");
        P8 = aM.DW("12");
        ei = aM.DW("13");
        nw = aM.DW("14");
        SI = aM.DW("15");
        KD = aM.DW("16");
        ro = aM.DW("17");
        cn = aM.DW("18");
        sh = aM.DW("19");
        cb = aM.DW("20");
        dx = XL.DW("1");
        sG = dx.DW("1");
        ef = dx.DW("2");
        Sf = dx.DW("3");
        vJ = dx.DW("4");
        g3 = dx.DW("5");
        Mz = dx.DW("6");
        I = dx.DW("7");
        ca = new bnm("1.2.840.10040.4.1");
        x9 = new bnm("1.2.840.10040.4.3");
        Qq = new bnm("1.3.133.16.840.63.0");
        sy = Qq.DW("2");
        aj = Qq.DW("3");
        lp = Qq.DW("16");
        OW = new bnm("1.2.840.10046");
        br = OW.DW("2.1");
        XX = OW.DW("3");
        kQ = XX.DW("1");
        yO = XX.DW("2");
        XG = XX.DW("3");
        jJ = XX.DW("4");
        wc = XX.DW("5");
        et = XX.DW("6");
        CU = XX.DW("7");
        Xa = XX.DW("8");
    }
}
