class dg {
    public int BT;
    public boolean DW;
    public int EQ;
    public boolean FH;
    public boolean Hw;
    public int J0;
    public int J8;
    public String KD;
    public fb Mr;
    public int P8;
    public int QX;
    public boolean SI;
    public fd U2;
    public int VH;
    public int Ws;
    public boolean XL;
    public int Zo;
    public fd a8;
    public boolean aM;
    public fd cb;
    public boolean cn;
    public int ei;
    public fy er;
    public dy gW;
    public int gn;
    public fb j3;
    public int j6;
    public fy lg;
    public long nw;
    public fh rN;
    public boolean ro;
    public fb sh;
    public int tp;
    public int u7;
    public int v5;
    public boolean vy;
    public int we;
    public fb yS;

    private dg() {
    }
}
